// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Functions      string
	GooseDBVersion string
	Users          string
}{
	Functions:      "functions",
	GooseDBVersion: "goose_db_version",
	Users:          "users",
}
