// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comms.proto

package comms

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	To                   uint64   `protobuf:"varint,1,opt,name=to,proto3" json:"to,omitempty"`
	From                 uint64   `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Spawn                string   `protobuf:"bytes,4,opt,name=spawn,proto3" json:"spawn,omitempty"`
	SpawnAddress         uint64   `protobuf:"varint,5,opt,name=spawn_address,json=spawnAddress,proto3" json:"spawn_address,omitempty"`
	Exit                 int32    `protobuf:"varint,6,opt,name=exit,proto3" json:"exit,omitempty"`
	YourAddress          uint64   `protobuf:"varint,7,opt,name=your_address,json=yourAddress,proto3" json:"your_address,omitempty"`
	ParentAddress        uint64   `protobuf:"varint,8,opt,name=parent_address,json=parentAddress,proto3" json:"parent_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetTo() uint64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *Message) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetSpawn() string {
	if m != nil {
		return m.Spawn
	}
	return ""
}

func (m *Message) GetSpawnAddress() uint64 {
	if m != nil {
		return m.SpawnAddress
	}
	return 0
}

func (m *Message) GetExit() int32 {
	if m != nil {
		return m.Exit
	}
	return 0
}

func (m *Message) GetYourAddress() uint64 {
	if m != nil {
		return m.YourAddress
	}
	return 0
}

func (m *Message) GetParentAddress() uint64 {
	if m != nil {
		return m.ParentAddress
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "comms.Message")
}

func init() { proto.RegisterFile("comms.proto", fileDescriptor_db39efb7717b7d47) }

var fileDescriptor_db39efb7717b7d47 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0x3b, 0x0e, 0xc2, 0x30,
	0x10, 0x44, 0xe5, 0x10, 0x27, 0xb0, 0xf9, 0x14, 0x16, 0x85, 0x4b, 0x03, 0x42, 0x72, 0x45, 0xc3,
	0x09, 0x38, 0x00, 0x8d, 0x2f, 0x80, 0x0c, 0x31, 0x88, 0x22, 0xd9, 0xc8, 0x36, 0x02, 0xae, 0xca,
	0x69, 0x50, 0x36, 0x90, 0xee, 0xed, 0xd3, 0xcc, 0x48, 0x0b, 0xc5, 0x05, 0xdb, 0x36, 0xec, 0x7a,
	0x8f, 0x11, 0x05, 0xa7, 0x63, 0xfd, 0x61, 0x90, 0x1f, 0x5d, 0x08, 0xf6, 0xe6, 0x44, 0x0d, 0x49,
	0x44, 0xc9, 0x14, 0xd3, 0xa9, 0x49, 0x22, 0x0a, 0x01, 0xe9, 0xd5, 0x63, 0x2b, 0x13, 0x32, 0xc4,
	0x83, 0x6b, 0x6c, 0xb4, 0x72, 0xa6, 0x98, 0x2e, 0x0d, 0xb1, 0x58, 0x02, 0x0f, 0xbd, 0x7d, 0x76,
	0x32, 0x55, 0x4c, 0x2f, 0xcc, 0x78, 0x88, 0x0d, 0x54, 0x04, 0x27, 0xdb, 0x34, 0xde, 0x85, 0x20,
	0x39, 0xcd, 0x94, 0x24, 0x0f, 0xa3, 0x1b, 0xe6, 0xdc, 0xeb, 0x1e, 0x65, 0xa6, 0x98, 0xe6, 0x86,
	0x58, 0xac, 0xa0, 0x7c, 0xe3, 0xc3, 0x4f, 0xbd, 0x9c, 0x7a, 0xc5, 0xe0, 0xfe, 0xb5, 0x2d, 0xd4,
	0xbd, 0xf5, 0xae, 0x8b, 0x53, 0x68, 0x4e, 0xa1, 0x6a, 0xb4, 0xbf, 0xd8, 0x39, 0xa3, 0x57, 0xf7,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x1c, 0x33, 0x46, 0xf9, 0x00, 0x00, 0x00,
}
