// This file is generated by rust-protobuf 2.10.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `comms.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_10_1;

#[derive(PartialEq,Clone,Default)]
pub struct Message {
    // message fields
    pub to: u64,
    pub from: u64,
    pub data: ::std::vec::Vec<u8>,
    pub spawn: ::std::string::String,
    pub spawn_address: u64,
    pub kill: bool,
    pub exiting: bool,
    pub exit: i32,
    pub your_address: u64,
    pub parent_address: u64,
    pub error: i32,
    pub startup: ::protobuf::SingularPtrField<Startup>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Message {
    fn default() -> &'a Message {
        <Message as ::protobuf::Message>::default_instance()
    }
}

impl Message {
    pub fn new() -> Message {
        ::std::default::Default::default()
    }

    // uint64 to = 1;


    pub fn get_to(&self) -> u64 {
        self.to
    }
    pub fn clear_to(&mut self) {
        self.to = 0;
    }

    // Param is passed by value, moved
    pub fn set_to(&mut self, v: u64) {
        self.to = v;
    }

    // uint64 from = 2;


    pub fn get_from(&self) -> u64 {
        self.from
    }
    pub fn clear_from(&mut self) {
        self.from = 0;
    }

    // Param is passed by value, moved
    pub fn set_from(&mut self, v: u64) {
        self.from = v;
    }

    // bytes data = 3;


    pub fn get_data(&self) -> &[u8] {
        &self.data
    }
    pub fn clear_data(&mut self) {
        self.data.clear();
    }

    // Param is passed by value, moved
    pub fn set_data(&mut self, v: ::std::vec::Vec<u8>) {
        self.data = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_data(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.data
    }

    // Take field
    pub fn take_data(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.data, ::std::vec::Vec::new())
    }

    // string spawn = 4;


    pub fn get_spawn(&self) -> &str {
        &self.spawn
    }
    pub fn clear_spawn(&mut self) {
        self.spawn.clear();
    }

    // Param is passed by value, moved
    pub fn set_spawn(&mut self, v: ::std::string::String) {
        self.spawn = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_spawn(&mut self) -> &mut ::std::string::String {
        &mut self.spawn
    }

    // Take field
    pub fn take_spawn(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.spawn, ::std::string::String::new())
    }

    // uint64 spawn_address = 5;


    pub fn get_spawn_address(&self) -> u64 {
        self.spawn_address
    }
    pub fn clear_spawn_address(&mut self) {
        self.spawn_address = 0;
    }

    // Param is passed by value, moved
    pub fn set_spawn_address(&mut self, v: u64) {
        self.spawn_address = v;
    }

    // bool kill = 6;


    pub fn get_kill(&self) -> bool {
        self.kill
    }
    pub fn clear_kill(&mut self) {
        self.kill = false;
    }

    // Param is passed by value, moved
    pub fn set_kill(&mut self, v: bool) {
        self.kill = v;
    }

    // bool exiting = 7;


    pub fn get_exiting(&self) -> bool {
        self.exiting
    }
    pub fn clear_exiting(&mut self) {
        self.exiting = false;
    }

    // Param is passed by value, moved
    pub fn set_exiting(&mut self, v: bool) {
        self.exiting = v;
    }

    // int32 exit = 8;


    pub fn get_exit(&self) -> i32 {
        self.exit
    }
    pub fn clear_exit(&mut self) {
        self.exit = 0;
    }

    // Param is passed by value, moved
    pub fn set_exit(&mut self, v: i32) {
        self.exit = v;
    }

    // uint64 your_address = 9;


    pub fn get_your_address(&self) -> u64 {
        self.your_address
    }
    pub fn clear_your_address(&mut self) {
        self.your_address = 0;
    }

    // Param is passed by value, moved
    pub fn set_your_address(&mut self, v: u64) {
        self.your_address = v;
    }

    // uint64 parent_address = 10;


    pub fn get_parent_address(&self) -> u64 {
        self.parent_address
    }
    pub fn clear_parent_address(&mut self) {
        self.parent_address = 0;
    }

    // Param is passed by value, moved
    pub fn set_parent_address(&mut self, v: u64) {
        self.parent_address = v;
    }

    // int32 error = 11;


    pub fn get_error(&self) -> i32 {
        self.error
    }
    pub fn clear_error(&mut self) {
        self.error = 0;
    }

    // Param is passed by value, moved
    pub fn set_error(&mut self, v: i32) {
        self.error = v;
    }

    // .comms.Startup startup = 12;


    pub fn get_startup(&self) -> &Startup {
        self.startup.as_ref().unwrap_or_else(|| Startup::default_instance())
    }
    pub fn clear_startup(&mut self) {
        self.startup.clear();
    }

    pub fn has_startup(&self) -> bool {
        self.startup.is_some()
    }

    // Param is passed by value, moved
    pub fn set_startup(&mut self, v: Startup) {
        self.startup = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_startup(&mut self) -> &mut Startup {
        if self.startup.is_none() {
            self.startup.set_default();
        }
        self.startup.as_mut().unwrap()
    }

    // Take field
    pub fn take_startup(&mut self) -> Startup {
        self.startup.take().unwrap_or_else(|| Startup::new())
    }
}

impl ::protobuf::Message for Message {
    fn is_initialized(&self) -> bool {
        for v in &self.startup {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.to = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.from = tmp;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.data)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.spawn)?;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.spawn_address = tmp;
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.kill = tmp;
                },
                7 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.exiting = tmp;
                },
                8 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.exit = tmp;
                },
                9 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.your_address = tmp;
                },
                10 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.parent_address = tmp;
                },
                11 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.error = tmp;
                },
                12 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.startup)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.to != 0 {
            my_size += ::protobuf::rt::value_size(1, self.to, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.from != 0 {
            my_size += ::protobuf::rt::value_size(2, self.from, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(3, &self.data);
        }
        if !self.spawn.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.spawn);
        }
        if self.spawn_address != 0 {
            my_size += ::protobuf::rt::value_size(5, self.spawn_address, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.kill != false {
            my_size += 2;
        }
        if self.exiting != false {
            my_size += 2;
        }
        if self.exit != 0 {
            my_size += ::protobuf::rt::value_size(8, self.exit, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.your_address != 0 {
            my_size += ::protobuf::rt::value_size(9, self.your_address, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.parent_address != 0 {
            my_size += ::protobuf::rt::value_size(10, self.parent_address, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.error != 0 {
            my_size += ::protobuf::rt::value_size(11, self.error, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(ref v) = self.startup.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.to != 0 {
            os.write_uint64(1, self.to)?;
        }
        if self.from != 0 {
            os.write_uint64(2, self.from)?;
        }
        if !self.data.is_empty() {
            os.write_bytes(3, &self.data)?;
        }
        if !self.spawn.is_empty() {
            os.write_string(4, &self.spawn)?;
        }
        if self.spawn_address != 0 {
            os.write_uint64(5, self.spawn_address)?;
        }
        if self.kill != false {
            os.write_bool(6, self.kill)?;
        }
        if self.exiting != false {
            os.write_bool(7, self.exiting)?;
        }
        if self.exit != 0 {
            os.write_int32(8, self.exit)?;
        }
        if self.your_address != 0 {
            os.write_uint64(9, self.your_address)?;
        }
        if self.parent_address != 0 {
            os.write_uint64(10, self.parent_address)?;
        }
        if self.error != 0 {
            os.write_int32(11, self.error)?;
        }
        if let Some(ref v) = self.startup.as_ref() {
            os.write_tag(12, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Message {
        Message::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "to",
                    |m: &Message| { &m.to },
                    |m: &mut Message| { &mut m.to },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "from",
                    |m: &Message| { &m.from },
                    |m: &mut Message| { &mut m.from },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "data",
                    |m: &Message| { &m.data },
                    |m: &mut Message| { &mut m.data },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "spawn",
                    |m: &Message| { &m.spawn },
                    |m: &mut Message| { &mut m.spawn },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "spawn_address",
                    |m: &Message| { &m.spawn_address },
                    |m: &mut Message| { &mut m.spawn_address },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "kill",
                    |m: &Message| { &m.kill },
                    |m: &mut Message| { &mut m.kill },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "exiting",
                    |m: &Message| { &m.exiting },
                    |m: &mut Message| { &mut m.exiting },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "exit",
                    |m: &Message| { &m.exit },
                    |m: &mut Message| { &mut m.exit },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "your_address",
                    |m: &Message| { &m.your_address },
                    |m: &mut Message| { &mut m.your_address },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "parent_address",
                    |m: &Message| { &m.parent_address },
                    |m: &mut Message| { &mut m.parent_address },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "error",
                    |m: &Message| { &m.error },
                    |m: &mut Message| { &mut m.error },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Startup>>(
                    "startup",
                    |m: &Message| { &m.startup },
                    |m: &mut Message| { &mut m.startup },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Message>(
                    "Message",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Message {
        static mut instance: ::protobuf::lazy::Lazy<Message> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Message,
        };
        unsafe {
            instance.get(Message::new)
        }
    }
}

impl ::protobuf::Clear for Message {
    fn clear(&mut self) {
        self.to = 0;
        self.from = 0;
        self.data.clear();
        self.spawn.clear();
        self.spawn_address = 0;
        self.kill = false;
        self.exiting = false;
        self.exit = 0;
        self.your_address = 0;
        self.parent_address = 0;
        self.error = 0;
        self.startup.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Message {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Message {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Startup {
    // message fields
    pub module: ::std::string::String,
    pub addr: u64,
    pub parent: u64,
    pub dbs: ::protobuf::RepeatedField<DB>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Startup {
    fn default() -> &'a Startup {
        <Startup as ::protobuf::Message>::default_instance()
    }
}

impl Startup {
    pub fn new() -> Startup {
        ::std::default::Default::default()
    }

    // string module = 1;


    pub fn get_module(&self) -> &str {
        &self.module
    }
    pub fn clear_module(&mut self) {
        self.module.clear();
    }

    // Param is passed by value, moved
    pub fn set_module(&mut self, v: ::std::string::String) {
        self.module = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_module(&mut self) -> &mut ::std::string::String {
        &mut self.module
    }

    // Take field
    pub fn take_module(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.module, ::std::string::String::new())
    }

    // uint64 addr = 2;


    pub fn get_addr(&self) -> u64 {
        self.addr
    }
    pub fn clear_addr(&mut self) {
        self.addr = 0;
    }

    // Param is passed by value, moved
    pub fn set_addr(&mut self, v: u64) {
        self.addr = v;
    }

    // uint64 parent = 3;


    pub fn get_parent(&self) -> u64 {
        self.parent
    }
    pub fn clear_parent(&mut self) {
        self.parent = 0;
    }

    // Param is passed by value, moved
    pub fn set_parent(&mut self, v: u64) {
        self.parent = v;
    }

    // repeated .comms.DB dbs = 4;


    pub fn get_dbs(&self) -> &[DB] {
        &self.dbs
    }
    pub fn clear_dbs(&mut self) {
        self.dbs.clear();
    }

    // Param is passed by value, moved
    pub fn set_dbs(&mut self, v: ::protobuf::RepeatedField<DB>) {
        self.dbs = v;
    }

    // Mutable pointer to the field.
    pub fn mut_dbs(&mut self) -> &mut ::protobuf::RepeatedField<DB> {
        &mut self.dbs
    }

    // Take field
    pub fn take_dbs(&mut self) -> ::protobuf::RepeatedField<DB> {
        ::std::mem::replace(&mut self.dbs, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for Startup {
    fn is_initialized(&self) -> bool {
        for v in &self.dbs {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.module)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.addr = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.parent = tmp;
                },
                4 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.dbs)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.module.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.module);
        }
        if self.addr != 0 {
            my_size += ::protobuf::rt::value_size(2, self.addr, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.parent != 0 {
            my_size += ::protobuf::rt::value_size(3, self.parent, ::protobuf::wire_format::WireTypeVarint);
        }
        for value in &self.dbs {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.module.is_empty() {
            os.write_string(1, &self.module)?;
        }
        if self.addr != 0 {
            os.write_uint64(2, self.addr)?;
        }
        if self.parent != 0 {
            os.write_uint64(3, self.parent)?;
        }
        for v in &self.dbs {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Startup {
        Startup::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "module",
                    |m: &Startup| { &m.module },
                    |m: &mut Startup| { &mut m.module },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "addr",
                    |m: &Startup| { &m.addr },
                    |m: &mut Startup| { &mut m.addr },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "parent",
                    |m: &Startup| { &m.parent },
                    |m: &mut Startup| { &mut m.parent },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<DB>>(
                    "dbs",
                    |m: &Startup| { &m.dbs },
                    |m: &mut Startup| { &mut m.dbs },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Startup>(
                    "Startup",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Startup {
        static mut instance: ::protobuf::lazy::Lazy<Startup> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Startup,
        };
        unsafe {
            instance.get(Startup::new)
        }
    }
}

impl ::protobuf::Clear for Startup {
    fn clear(&mut self) {
        self.module.clear();
        self.addr = 0;
        self.parent = 0;
        self.dbs.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Startup {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Startup {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct DB {
    // message fields
    pub field_type: ::std::string::String,
    pub name: ::std::string::String,
    pub connection: ::std::string::String,
    pub token: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a DB {
    fn default() -> &'a DB {
        <DB as ::protobuf::Message>::default_instance()
    }
}

impl DB {
    pub fn new() -> DB {
        ::std::default::Default::default()
    }

    // string type = 1;


    pub fn get_field_type(&self) -> &str {
        &self.field_type
    }
    pub fn clear_field_type(&mut self) {
        self.field_type.clear();
    }

    // Param is passed by value, moved
    pub fn set_field_type(&mut self, v: ::std::string::String) {
        self.field_type = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_field_type(&mut self) -> &mut ::std::string::String {
        &mut self.field_type
    }

    // Take field
    pub fn take_field_type(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.field_type, ::std::string::String::new())
    }

    // string name = 2;


    pub fn get_name(&self) -> &str {
        &self.name
    }
    pub fn clear_name(&mut self) {
        self.name.clear();
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        &mut self.name
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.name, ::std::string::String::new())
    }

    // string connection = 3;


    pub fn get_connection(&self) -> &str {
        &self.connection
    }
    pub fn clear_connection(&mut self) {
        self.connection.clear();
    }

    // Param is passed by value, moved
    pub fn set_connection(&mut self, v: ::std::string::String) {
        self.connection = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_connection(&mut self) -> &mut ::std::string::String {
        &mut self.connection
    }

    // Take field
    pub fn take_connection(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.connection, ::std::string::String::new())
    }

    // string token = 4;


    pub fn get_token(&self) -> &str {
        &self.token
    }
    pub fn clear_token(&mut self) {
        self.token.clear();
    }

    // Param is passed by value, moved
    pub fn set_token(&mut self, v: ::std::string::String) {
        self.token = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_token(&mut self) -> &mut ::std::string::String {
        &mut self.token
    }

    // Take field
    pub fn take_token(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.token, ::std::string::String::new())
    }
}

impl ::protobuf::Message for DB {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.field_type)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.name)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.connection)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.token)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.field_type.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.field_type);
        }
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.name);
        }
        if !self.connection.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.connection);
        }
        if !self.token.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.token);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.field_type.is_empty() {
            os.write_string(1, &self.field_type)?;
        }
        if !self.name.is_empty() {
            os.write_string(2, &self.name)?;
        }
        if !self.connection.is_empty() {
            os.write_string(3, &self.connection)?;
        }
        if !self.token.is_empty() {
            os.write_string(4, &self.token)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> DB {
        DB::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "type",
                    |m: &DB| { &m.field_type },
                    |m: &mut DB| { &mut m.field_type },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "name",
                    |m: &DB| { &m.name },
                    |m: &mut DB| { &mut m.name },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "connection",
                    |m: &DB| { &m.connection },
                    |m: &mut DB| { &mut m.connection },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "token",
                    |m: &DB| { &m.token },
                    |m: &mut DB| { &mut m.token },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<DB>(
                    "DB",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static DB {
        static mut instance: ::protobuf::lazy::Lazy<DB> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const DB,
        };
        unsafe {
            instance.get(DB::new)
        }
    }
}

impl ::protobuf::Clear for DB {
    fn clear(&mut self) {
        self.field_type.clear();
        self.name.clear();
        self.connection.clear();
        self.token.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for DB {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DB {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0bcomms.proto\x12\x05comms\"\xc8\x02\n\x07Message\x12\x0e\n\x02to\
    \x18\x01\x20\x01(\x04R\x02to\x12\x12\n\x04from\x18\x02\x20\x01(\x04R\x04\
    from\x12\x12\n\x04data\x18\x03\x20\x01(\x0cR\x04data\x12\x14\n\x05spawn\
    \x18\x04\x20\x01(\tR\x05spawn\x12#\n\rspawn_address\x18\x05\x20\x01(\x04\
    R\x0cspawnAddress\x12\x12\n\x04kill\x18\x06\x20\x01(\x08R\x04kill\x12\
    \x18\n\x07exiting\x18\x07\x20\x01(\x08R\x07exiting\x12\x12\n\x04exit\x18\
    \x08\x20\x01(\x05R\x04exit\x12!\n\x0cyour_address\x18\t\x20\x01(\x04R\
    \x0byourAddress\x12%\n\x0eparent_address\x18\n\x20\x01(\x04R\rparentAddr\
    ess\x12\x14\n\x05error\x18\x0b\x20\x01(\x05R\x05error\x12(\n\x07startup\
    \x18\x0c\x20\x01(\x0b2\x0e.comms.StartupR\x07startup\"j\n\x07Startup\x12\
    \x16\n\x06module\x18\x01\x20\x01(\tR\x06module\x12\x12\n\x04addr\x18\x02\
    \x20\x01(\x04R\x04addr\x12\x16\n\x06parent\x18\x03\x20\x01(\x04R\x06pare\
    nt\x12\x1b\n\x03dbs\x18\x04\x20\x03(\x0b2\t.comms.DBR\x03dbs\"b\n\x02DB\
    \x12\x12\n\x04type\x18\x01\x20\x01(\tR\x04type\x12\x12\n\x04name\x18\x02\
    \x20\x01(\tR\x04name\x12\x1e\n\nconnection\x18\x03\x20\x01(\tR\nconnecti\
    on\x12\x14\n\x05token\x18\x04\x20\x01(\tR\x05tokenb\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
