// Code generated by protoc-gen-go. DO NOT EDIT.
// source: http.proto

package httpproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Http_Method int32

const (
	Http_GET     Http_Method = 0
	Http_PUT     Http_Method = 1
	Http_POST    Http_Method = 2
	Http_DELETE  Http_Method = 3
	Http_PATCH   Http_Method = 4
	Http_OPTIONS Http_Method = 5
	Http_TRACE   Http_Method = 6
	Http_CONNECT Http_Method = 7
)

var Http_Method_name = map[int32]string{
	0: "GET",
	1: "PUT",
	2: "POST",
	3: "DELETE",
	4: "PATCH",
	5: "OPTIONS",
	6: "TRACE",
	7: "CONNECT",
}

var Http_Method_value = map[string]int32{
	"GET":     0,
	"PUT":     1,
	"POST":    2,
	"DELETE":  3,
	"PATCH":   4,
	"OPTIONS": 5,
	"TRACE":   6,
	"CONNECT": 7,
}

func (x Http_Method) String() string {
	return proto.EnumName(Http_Method_name, int32(x))
}

func (Http_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{0, 0}
}

type Http struct {
	ProtoMajor int32                  `protobuf:"varint,1,opt,name=proto_major,json=protoMajor,proto3" json:"proto_major,omitempty"`
	ProtoMinor int32                  `protobuf:"varint,2,opt,name=proto_minor,json=protoMinor,proto3" json:"proto_minor,omitempty"`
	Uri        string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Status     int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Headers    map[string]*HeaderList `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Method     Http_Method            `protobuf:"varint,6,opt,name=method,proto3,enum=httpproto.Http_Method" json:"method,omitempty"`
	Body       []byte                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	// this is a hack, we just say when the request is over
	// but http already handles this, so maybe remove it and implement
	// more complex detection of request completion?
	Eof                  bool     `protobuf:"varint,8,opt,name=eof,proto3" json:"eof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Http) Reset()         { *m = Http{} }
func (m *Http) String() string { return proto.CompactTextString(m) }
func (*Http) ProtoMessage()    {}
func (*Http) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{0}
}

func (m *Http) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Http.Unmarshal(m, b)
}
func (m *Http) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Http.Marshal(b, m, deterministic)
}
func (m *Http) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Http.Merge(m, src)
}
func (m *Http) XXX_Size() int {
	return xxx_messageInfo_Http.Size(m)
}
func (m *Http) XXX_DiscardUnknown() {
	xxx_messageInfo_Http.DiscardUnknown(m)
}

var xxx_messageInfo_Http proto.InternalMessageInfo

func (m *Http) GetProtoMajor() int32 {
	if m != nil {
		return m.ProtoMajor
	}
	return 0
}

func (m *Http) GetProtoMinor() int32 {
	if m != nil {
		return m.ProtoMinor
	}
	return 0
}

func (m *Http) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Http) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Http) GetHeaders() map[string]*HeaderList {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Http) GetMethod() Http_Method {
	if m != nil {
		return m.Method
	}
	return Http_GET
}

func (m *Http) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Http) GetEof() bool {
	if m != nil {
		return m.Eof
	}
	return false
}

type HeaderList struct {
	Header               []string `protobuf:"bytes,1,rep,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeaderList) Reset()         { *m = HeaderList{} }
func (m *HeaderList) String() string { return proto.CompactTextString(m) }
func (*HeaderList) ProtoMessage()    {}
func (*HeaderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{1}
}

func (m *HeaderList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderList.Unmarshal(m, b)
}
func (m *HeaderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderList.Marshal(b, m, deterministic)
}
func (m *HeaderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderList.Merge(m, src)
}
func (m *HeaderList) XXX_Size() int {
	return xxx_messageInfo_HeaderList.Size(m)
}
func (m *HeaderList) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderList.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderList proto.InternalMessageInfo

func (m *HeaderList) GetHeader() []string {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterEnum("httpproto.Http_Method", Http_Method_name, Http_Method_value)
	proto.RegisterType((*Http)(nil), "httpproto.Http")
	proto.RegisterMapType((map[string]*HeaderList)(nil), "httpproto.Http.HeadersEntry")
	proto.RegisterType((*HeaderList)(nil), "httpproto.HeaderList")
}

func init() { proto.RegisterFile("http.proto", fileDescriptor_11b04836674e6f94) }

var fileDescriptor_11b04836674e6f94 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xdf, 0x4b, 0xeb, 0x30,
	0x14, 0xc7, 0x6f, 0xd6, 0x5f, 0xeb, 0xe9, 0xb8, 0x84, 0x03, 0x77, 0x84, 0x8b, 0x60, 0x19, 0x3e,
	0x14, 0x84, 0x3e, 0x4c, 0x10, 0xf1, 0x6d, 0xd4, 0xe2, 0x84, 0x6d, 0xad, 0x59, 0x7c, 0xd6, 0x8e,
	0x55, 0x36, 0x75, 0xcb, 0x68, 0x33, 0x61, 0x7f, 0x98, 0xff, 0x9f, 0x24, 0x9d, 0x5a, 0x7c, 0xfb,
	0xe4, 0x9b, 0x4f, 0x38, 0xdf, 0x1c, 0x80, 0x95, 0x52, 0xbb, 0x78, 0x57, 0x49, 0x25, 0xd1, 0xd7,
	0x6c, 0x70, 0xf0, 0x61, 0x81, 0x3d, 0x56, 0x6a, 0x87, 0xa7, 0x10, 0x98, 0xe4, 0x71, 0x53, 0xbc,
	0xc8, 0x8a, 0x91, 0x90, 0x44, 0x0e, 0x07, 0x13, 0x4d, 0x75, 0xd2, 0x12, 0xd6, 0x5b, 0x59, 0xb1,
	0x4e, 0x5b, 0xd0, 0x09, 0x52, 0xb0, 0xf6, 0xd5, 0x9a, 0x59, 0x21, 0x89, 0x7c, 0xae, 0x11, 0xfb,
	0xe0, 0xd6, 0xaa, 0x50, 0xfb, 0x9a, 0xd9, 0xc6, 0x3e, 0x9e, 0xf0, 0x12, 0xbc, 0x55, 0x59, 0x2c,
	0xcb, 0xaa, 0x66, 0x4e, 0x68, 0x45, 0xc1, 0xf0, 0x24, 0xfe, 0x6e, 0x14, 0xeb, 0x36, 0xf1, 0xb8,
	0xb9, 0x4e, 0xb7, 0xaa, 0x3a, 0xf0, 0x2f, 0x19, 0x63, 0x70, 0x37, 0xa5, 0x5a, 0xc9, 0x25, 0x73,
	0x43, 0x12, 0xfd, 0x1d, 0xf6, 0x7f, 0x3f, 0x9b, 0x9a, 0x5b, 0x7e, 0xb4, 0x10, 0xc1, 0x5e, 0xc8,
	0xe5, 0x81, 0x79, 0x21, 0x89, 0x7a, 0xdc, 0xb0, 0x6e, 0x59, 0xca, 0x67, 0xd6, 0x0d, 0x49, 0xd4,
	0xe5, 0x1a, 0xff, 0xdf, 0x43, 0xaf, 0x3d, 0x4e, 0x1b, 0xaf, 0xe5, 0xc1, 0x6c, 0xc0, 0xe7, 0x1a,
	0xf1, 0x1c, 0x9c, 0xf7, 0xe2, 0x6d, 0x5f, 0x9a, 0x4f, 0x07, 0xc3, 0x7f, 0xed, 0xb1, 0xe6, 0xe5,
	0x64, 0x5d, 0x2b, 0xde, 0x38, 0xd7, 0x9d, 0x2b, 0x32, 0x78, 0x02, 0xb7, 0xa9, 0x82, 0x1e, 0x58,
	0xb7, 0xa9, 0xa0, 0x7f, 0x34, 0xe4, 0x0f, 0x82, 0x12, 0xec, 0x82, 0x9d, 0x67, 0x73, 0x41, 0x3b,
	0x08, 0xe0, 0xde, 0xa4, 0x93, 0x54, 0xa4, 0xd4, 0x42, 0x1f, 0x9c, 0x7c, 0x24, 0x92, 0x31, 0xb5,
	0x31, 0x00, 0x2f, 0xcb, 0xc5, 0x5d, 0x36, 0x9b, 0x53, 0x47, 0xe7, 0x82, 0x8f, 0x92, 0x94, 0xba,
	0x3a, 0x4f, 0xb2, 0xd9, 0x2c, 0x4d, 0x04, 0xf5, 0x06, 0x67, 0x00, 0x3f, 0xa3, 0xf5, 0xa2, 0x9b,
	0x1d, 0x31, 0x12, 0x5a, 0x91, 0xcf, 0x8f, 0xa7, 0x85, 0x6b, 0x4a, 0x5e, 0x7c, 0x06, 0x00, 0x00,
	0xff, 0xff, 0x6f, 0x26, 0xa5, 0x9d, 0xfd, 0x01, 0x00, 0x00,
}
