// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nixbuild.proto

package nixbuildpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientPayload struct {
	Build                *Build          `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	File                 *CompressedFile `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ClientPayload) Reset()         { *m = ClientPayload{} }
func (m *ClientPayload) String() string { return proto.CompactTextString(m) }
func (*ClientPayload) ProtoMessage()    {}
func (*ClientPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{0}
}

func (m *ClientPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientPayload.Unmarshal(m, b)
}
func (m *ClientPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientPayload.Marshal(b, m, deterministic)
}
func (m *ClientPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientPayload.Merge(m, src)
}
func (m *ClientPayload) XXX_Size() int {
	return xxx_messageInfo_ClientPayload.Size(m)
}
func (m *ClientPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ClientPayload proto.InternalMessageInfo

func (m *ClientPayload) GetBuild() *Build {
	if m != nil {
		return m.Build
	}
	return nil
}

func (m *ClientPayload) GetFile() *CompressedFile {
	if m != nil {
		return m.File
	}
	return nil
}

type CompressedFile struct {
	Body                 []byte   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RequestedHash        []byte   `protobuf:"bytes,3,opt,name=requested_hash,json=requestedHash,proto3" json:"requested_hash,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompressedFile) Reset()         { *m = CompressedFile{} }
func (m *CompressedFile) String() string { return proto.CompactTextString(m) }
func (*CompressedFile) ProtoMessage()    {}
func (*CompressedFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{1}
}

func (m *CompressedFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompressedFile.Unmarshal(m, b)
}
func (m *CompressedFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompressedFile.Marshal(b, m, deterministic)
}
func (m *CompressedFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompressedFile.Merge(m, src)
}
func (m *CompressedFile) XXX_Size() int {
	return xxx_messageInfo_CompressedFile.Size(m)
}
func (m *CompressedFile) XXX_DiscardUnknown() {
	xxx_messageInfo_CompressedFile.DiscardUnknown(m)
}

var xxx_messageInfo_CompressedFile proto.InternalMessageInfo

func (m *CompressedFile) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *CompressedFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CompressedFile) GetRequestedHash() []byte {
	if m != nil {
		return m.RequestedHash
	}
	return nil
}

func (m *CompressedFile) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ServerPayload struct {
	Files                []*CompressedFile `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	HashNeeded           []*HashRequest    `protobuf:"bytes,2,rep,name=hash_needed,json=hashNeeded,proto3" json:"hash_needed,omitempty"`
	Log                  [][]byte          `protobuf:"bytes,3,rep,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ServerPayload) Reset()         { *m = ServerPayload{} }
func (m *ServerPayload) String() string { return proto.CompactTextString(m) }
func (*ServerPayload) ProtoMessage()    {}
func (*ServerPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{2}
}

func (m *ServerPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerPayload.Unmarshal(m, b)
}
func (m *ServerPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerPayload.Marshal(b, m, deterministic)
}
func (m *ServerPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerPayload.Merge(m, src)
}
func (m *ServerPayload) XXX_Size() int {
	return xxx_messageInfo_ServerPayload.Size(m)
}
func (m *ServerPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ServerPayload proto.InternalMessageInfo

func (m *ServerPayload) GetFiles() []*CompressedFile {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *ServerPayload) GetHashNeeded() []*HashRequest {
	if m != nil {
		return m.HashNeeded
	}
	return nil
}

func (m *ServerPayload) GetLog() [][]byte {
	if m != nil {
		return m.Log
	}
	return nil
}

type HashRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashRequest) Reset()         { *m = HashRequest{} }
func (m *HashRequest) String() string { return proto.CompactTextString(m) }
func (*HashRequest) ProtoMessage()    {}
func (*HashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{3}
}

func (m *HashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashRequest.Unmarshal(m, b)
}
func (m *HashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashRequest.Marshal(b, m, deterministic)
}
func (m *HashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashRequest.Merge(m, src)
}
func (m *HashRequest) XXX_Size() int {
	return xxx_messageInfo_HashRequest.Size(m)
}
func (m *HashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HashRequest proto.InternalMessageInfo

func (m *HashRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *HashRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Build struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Files                []*File  `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	BuildLocation        string   `protobuf:"bytes,3,opt,name=build_location,json=buildLocation,proto3" json:"build_location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{4}
}

func (m *Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build.Unmarshal(m, b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build.Marshal(b, m, deterministic)
}
func (m *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(m, src)
}
func (m *Build) XXX_Size() int {
	return xxx_messageInfo_Build.Size(m)
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

func (m *Build) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Build) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *Build) GetBuildLocation() string {
	if m != nil {
		return m.BuildLocation
	}
	return ""
}

type File struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsDir                bool     `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Hash                 []byte   `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{5}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type HealthPayload struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthPayload) Reset()         { *m = HealthPayload{} }
func (m *HealthPayload) String() string { return proto.CompactTextString(m) }
func (*HealthPayload) ProtoMessage()    {}
func (*HealthPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{6}
}

func (m *HealthPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthPayload.Unmarshal(m, b)
}
func (m *HealthPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthPayload.Marshal(b, m, deterministic)
}
func (m *HealthPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthPayload.Merge(m, src)
}
func (m *HealthPayload) XXX_Size() int {
	return xxx_messageInfo_HealthPayload.Size(m)
}
func (m *HealthPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthPayload.DiscardUnknown(m)
}

var xxx_messageInfo_HealthPayload proto.InternalMessageInfo

type HealthResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{7}
}

func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (m *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(m, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HealthResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ClientPayload)(nil), "nixbuildpb.ClientPayload")
	proto.RegisterType((*CompressedFile)(nil), "nixbuildpb.CompressedFile")
	proto.RegisterType((*ServerPayload)(nil), "nixbuildpb.ServerPayload")
	proto.RegisterType((*HashRequest)(nil), "nixbuildpb.HashRequest")
	proto.RegisterType((*Build)(nil), "nixbuildpb.Build")
	proto.RegisterType((*File)(nil), "nixbuildpb.File")
	proto.RegisterType((*HealthPayload)(nil), "nixbuildpb.HealthPayload")
	proto.RegisterType((*HealthResponse)(nil), "nixbuildpb.HealthResponse")
}

func init() { proto.RegisterFile("nixbuild.proto", fileDescriptor_7ac32869e13b7ce8) }

var fileDescriptor_7ac32869e13b7ce8 = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x95, 0x9b, 0xa6, 0x62, 0xa7, 0x4d, 0x58, 0x2c, 0x21, 0x42, 0x4f, 0x55, 0xa4, 0x85, 0x9e,
	0xaa, 0xd5, 0x22, 0x10, 0x37, 0x04, 0x8b, 0xd0, 0x1e, 0x10, 0x42, 0xe6, 0x03, 0x2a, 0xb7, 0x1e,
	0x36, 0x46, 0x6e, 0x1c, 0xe2, 0x2c, 0xa2, 0xfc, 0x03, 0x17, 0xbe, 0x18, 0x79, 0xdc, 0xb4, 0x8e,
	0x40, 0xda, 0x53, 0xa7, 0x6f, 0xde, 0xd8, 0xef, 0xbd, 0x71, 0x20, 0xaf, 0xf5, 0xcf, 0xcd, 0x9d,
	0x36, 0x6a, 0xd5, 0xb4, 0xb6, 0xb3, 0x1c, 0xfa, 0xff, 0xcd, 0xa6, 0xac, 0x20, 0xbb, 0x36, 0x1a,
	0xeb, 0xee, 0xb3, 0xdc, 0x1b, 0x2b, 0x15, 0x7f, 0x0e, 0x29, 0xf5, 0x0a, 0xb6, 0x60, 0xcb, 0xe9,
	0xd5, 0xa3, 0xd5, 0x89, 0xbc, 0x7a, 0xe7, 0x7f, 0x45, 0xe8, 0xf3, 0x15, 0x8c, 0xbf, 0x6a, 0x83,
	0xc5, 0x88, 0x78, 0xf3, 0x98, 0x77, 0x6d, 0x77, 0x4d, 0x8b, 0xce, 0xa1, 0xfa, 0xa0, 0x0d, 0x0a,
	0xe2, 0x95, 0x0e, 0xf2, 0x21, 0xce, 0x39, 0x8c, 0x37, 0x56, 0xed, 0xe9, 0xa6, 0x99, 0xa0, 0xda,
	0x63, 0xb5, 0xdc, 0x85, 0x53, 0xcf, 0x04, 0xd5, 0xfc, 0x02, 0xf2, 0x16, 0xbf, 0xdf, 0xa1, 0xeb,
	0x50, 0xad, 0x2b, 0xe9, 0xaa, 0x22, 0xa1, 0x89, 0xec, 0x88, 0xde, 0x48, 0x57, 0xf9, 0xd1, 0x46,
	0x76, 0x55, 0x31, 0x0e, 0xa3, 0xbe, 0x2e, 0x7f, 0x33, 0xc8, 0xbe, 0x60, 0xfb, 0x03, 0xdb, 0xde,
	0xdf, 0x25, 0xa4, 0x5e, 0x8e, 0x2b, 0xd8, 0x22, 0xb9, 0x47, 0x77, 0x20, 0xf2, 0xd7, 0x30, 0xf5,
	0x97, 0xae, 0x6b, 0x44, 0x85, 0xaa, 0x18, 0xd1, 0xdc, 0x93, 0x78, 0xce, 0x5f, 0x2f, 0x82, 0x16,
	0x01, 0x9e, 0xfb, 0x89, 0xa8, 0xfc, 0x1c, 0x12, 0x63, 0x6f, 0x8b, 0x64, 0x91, 0x2c, 0x67, 0xc2,
	0x97, 0xe5, 0x4b, 0x98, 0x46, 0x64, 0x2f, 0x99, 0xfc, 0x1c, 0x12, 0xa8, 0x62, 0x1b, 0xa3, 0xc8,
	0xc6, 0x37, 0x48, 0x29, 0xfb, 0x63, 0x3c, 0x2c, 0x8a, 0xe7, 0x59, 0xef, 0x28, 0x28, 0x3b, 0x8f,
	0x95, 0xc5, 0x3e, 0x2e, 0x20, 0x27, 0x78, 0x6d, 0xec, 0x56, 0x76, 0xda, 0xd6, 0x14, 0xe3, 0x99,
	0xc8, 0x08, 0xfd, 0x78, 0x00, 0xcb, 0x1d, 0x8c, 0xfb, 0xed, 0x90, 0x0e, 0x76, 0xd2, 0xf1, 0xdf,
	0xed, 0x3c, 0x86, 0x89, 0x76, 0x6b, 0xa5, 0x5b, 0x3a, 0xee, 0x81, 0x48, 0xb5, 0x7b, 0xaf, 0x5b,
	0x4f, 0x75, 0xfa, 0x17, 0xd2, 0x36, 0x12, 0x41, 0xf5, 0xd1, 0x6e, 0x7a, 0xb2, 0x5b, 0x3e, 0x84,
	0xec, 0x06, 0xa5, 0xe9, 0xaa, 0xc3, 0x82, 0xca, 0x57, 0x90, 0x07, 0x40, 0xa0, 0x6b, 0x6c, 0xed,
	0x68, 0x6c, 0x6b, 0x55, 0x30, 0x9d, 0x0a, 0xaa, 0x7d, 0xb4, 0x3b, 0x77, 0x7b, 0x10, 0xe2, 0xcb,
	0xab, 0x3f, 0x0c, 0x66, 0x14, 0x92, 0xdf, 0xb7, 0xde, 0x22, 0x7f, 0xdb, 0x87, 0xf6, 0x74, 0xb0,
	0xe3, 0xf8, 0xb5, 0xcf, 0x07, 0xad, 0xc1, 0x43, 0x59, 0xb2, 0x4b, 0xc6, 0xdf, 0xc0, 0x24, 0x68,
	0x19, 0x9e, 0x31, 0x10, 0x3c, 0x9f, 0xff, 0xdb, 0xea, 0xa5, 0x6f, 0x26, 0xf4, 0xc5, 0xbd, 0xf8,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0xba, 0xeb, 0x4d, 0x43, 0x83, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BuildServiceClient is the client API for BuildService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BuildServiceClient interface {
	Build(ctx context.Context, opts ...grpc.CallOption) (BuildService_BuildClient, error)
	Health(ctx context.Context, in *HealthPayload, opts ...grpc.CallOption) (*HealthResponse, error)
}

type buildServiceClient struct {
	cc *grpc.ClientConn
}

func NewBuildServiceClient(cc *grpc.ClientConn) BuildServiceClient {
	return &buildServiceClient{cc}
}

func (c *buildServiceClient) Build(ctx context.Context, opts ...grpc.CallOption) (BuildService_BuildClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BuildService_serviceDesc.Streams[0], "/nixbuildpb.BuildService/Build", opts...)
	if err != nil {
		return nil, err
	}
	x := &buildServiceBuildClient{stream}
	return x, nil
}

type BuildService_BuildClient interface {
	Send(*ClientPayload) error
	Recv() (*ServerPayload, error)
	grpc.ClientStream
}

type buildServiceBuildClient struct {
	grpc.ClientStream
}

func (x *buildServiceBuildClient) Send(m *ClientPayload) error {
	return x.ClientStream.SendMsg(m)
}

func (x *buildServiceBuildClient) Recv() (*ServerPayload, error) {
	m := new(ServerPayload)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *buildServiceClient) Health(ctx context.Context, in *HealthPayload, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/nixbuildpb.BuildService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildServiceServer is the server API for BuildService service.
type BuildServiceServer interface {
	Build(BuildService_BuildServer) error
	Health(context.Context, *HealthPayload) (*HealthResponse, error)
}

// UnimplementedBuildServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBuildServiceServer struct {
}

func (*UnimplementedBuildServiceServer) Build(srv BuildService_BuildServer) error {
	return status.Errorf(codes.Unimplemented, "method Build not implemented")
}
func (*UnimplementedBuildServiceServer) Health(ctx context.Context, req *HealthPayload) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}

func RegisterBuildServiceServer(s *grpc.Server, srv BuildServiceServer) {
	s.RegisterService(&_BuildService_serviceDesc, srv)
}

func _BuildService_Build_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BuildServiceServer).Build(&buildServiceBuildServer{stream})
}

type BuildService_BuildServer interface {
	Send(*ServerPayload) error
	Recv() (*ClientPayload, error)
	grpc.ServerStream
}

type buildServiceBuildServer struct {
	grpc.ServerStream
}

func (x *buildServiceBuildServer) Send(m *ServerPayload) error {
	return x.ServerStream.SendMsg(m)
}

func (x *buildServiceBuildServer) Recv() (*ClientPayload, error) {
	m := new(ClientPayload)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BuildService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixbuildpb.BuildService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).Health(ctx, req.(*HealthPayload))
	}
	return interceptor(ctx, in, info, handler)
}

var _BuildService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nixbuildpb.BuildService",
	HandlerType: (*BuildServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _BuildService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Build",
			Handler:       _BuildService_Build_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "nixbuild.proto",
}
