// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nixbuild.proto

package nixbuildpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientPayload struct {
	Build                *Build   `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	Zip                  []byte   `protobuf:"bytes,2,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientPayload) Reset()         { *m = ClientPayload{} }
func (m *ClientPayload) String() string { return proto.CompactTextString(m) }
func (*ClientPayload) ProtoMessage()    {}
func (*ClientPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{0}
}

func (m *ClientPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientPayload.Unmarshal(m, b)
}
func (m *ClientPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientPayload.Marshal(b, m, deterministic)
}
func (m *ClientPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientPayload.Merge(m, src)
}
func (m *ClientPayload) XXX_Size() int {
	return xxx_messageInfo_ClientPayload.Size(m)
}
func (m *ClientPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ClientPayload proto.InternalMessageInfo

func (m *ClientPayload) GetBuild() *Build {
	if m != nil {
		return m.Build
	}
	return nil
}

func (m *ClientPayload) GetZip() []byte {
	if m != nil {
		return m.Zip
	}
	return nil
}

type ServerPayload struct {
	Files                []*OutFile `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	HashNeeded           [][]byte   `protobuf:"bytes,2,rep,name=hash_needed,json=hashNeeded,proto3" json:"hash_needed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServerPayload) Reset()         { *m = ServerPayload{} }
func (m *ServerPayload) String() string { return proto.CompactTextString(m) }
func (*ServerPayload) ProtoMessage()    {}
func (*ServerPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{1}
}

func (m *ServerPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerPayload.Unmarshal(m, b)
}
func (m *ServerPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerPayload.Marshal(b, m, deterministic)
}
func (m *ServerPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerPayload.Merge(m, src)
}
func (m *ServerPayload) XXX_Size() int {
	return xxx_messageInfo_ServerPayload.Size(m)
}
func (m *ServerPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ServerPayload proto.InternalMessageInfo

func (m *ServerPayload) GetFiles() []*OutFile {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *ServerPayload) GetHashNeeded() [][]byte {
	if m != nil {
		return m.HashNeeded
	}
	return nil
}

type OutFile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutFile) Reset()         { *m = OutFile{} }
func (m *OutFile) String() string { return proto.CompactTextString(m) }
func (*OutFile) ProtoMessage()    {}
func (*OutFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{2}
}

func (m *OutFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutFile.Unmarshal(m, b)
}
func (m *OutFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutFile.Marshal(b, m, deterministic)
}
func (m *OutFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutFile.Merge(m, src)
}
func (m *OutFile) XXX_Size() int {
	return xxx_messageInfo_OutFile.Size(m)
}
func (m *OutFile) XXX_DiscardUnknown() {
	xxx_messageInfo_OutFile.DiscardUnknown(m)
}

var xxx_messageInfo_OutFile proto.InternalMessageInfo

func (m *OutFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OutFile) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Build struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	BuildLocation        string   `protobuf:"bytes,2,opt,name=build_location,json=buildLocation,proto3" json:"build_location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{3}
}

func (m *Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build.Unmarshal(m, b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build.Marshal(b, m, deterministic)
}
func (m *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(m, src)
}
func (m *Build) XXX_Size() int {
	return xxx_messageInfo_Build.Size(m)
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

func (m *Build) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *Build) GetBuildLocation() string {
	if m != nil {
		return m.BuildLocation
	}
	return ""
}

type File struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsDir                bool     `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Hash                 []byte   `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{4}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientPayload)(nil), "nixbuildpb.ClientPayload")
	proto.RegisterType((*ServerPayload)(nil), "nixbuildpb.ServerPayload")
	proto.RegisterType((*OutFile)(nil), "nixbuildpb.OutFile")
	proto.RegisterType((*Build)(nil), "nixbuildpb.Build")
	proto.RegisterType((*File)(nil), "nixbuildpb.File")
}

func init() { proto.RegisterFile("nixbuild.proto", fileDescriptor_7ac32869e13b7ce8) }

var fileDescriptor_7ac32869e13b7ce8 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xcf, 0x4e, 0xe3, 0x30,
	0x10, 0xc6, 0xe5, 0xa6, 0x69, 0xb7, 0xd3, 0x3f, 0xea, 0x7a, 0xb5, 0x92, 0xe1, 0x42, 0x14, 0x09,
	0x30, 0x97, 0x0a, 0xca, 0x1b, 0x50, 0xc4, 0x01, 0x21, 0xa8, 0x0c, 0xe2, 0xc2, 0xa1, 0x72, 0x12,
	0xa3, 0x0c, 0x4a, 0xe3, 0xc8, 0x49, 0x11, 0xed, 0xd3, 0x23, 0xbb, 0x0d, 0x24, 0x27, 0x7f, 0xfe,
	0x66, 0x3c, 0xfa, 0xcd, 0x8c, 0x61, 0x92, 0xe3, 0x57, 0xb4, 0xc1, 0x2c, 0x99, 0x15, 0x46, 0x57,
	0x9a, 0x42, 0x7d, 0x2f, 0xa2, 0xf0, 0x1e, 0xc6, 0x8b, 0x0c, 0x55, 0x5e, 0x2d, 0xe5, 0x36, 0xd3,
	0x32, 0xa1, 0xe7, 0xe0, 0xbb, 0x18, 0x23, 0x01, 0xe1, 0xc3, 0xf9, 0xdf, 0xd9, 0x6f, 0xf2, 0xec,
	0xc6, 0x9e, 0x62, 0x1f, 0xa7, 0x53, 0xf0, 0x76, 0x58, 0xb0, 0x4e, 0x40, 0xf8, 0x48, 0x58, 0x19,
	0xbe, 0xc1, 0xf8, 0x59, 0x99, 0x4f, 0x65, 0xea, 0x5a, 0x17, 0xe0, 0xbf, 0x63, 0xa6, 0x4a, 0x46,
	0x02, 0x8f, 0x0f, 0xe7, 0xff, 0x9a, 0xb5, 0x9e, 0x36, 0xd5, 0x1d, 0x66, 0x4a, 0xec, 0x33, 0xe8,
	0x09, 0x0c, 0x53, 0x59, 0xa6, 0xab, 0x5c, 0xa9, 0x44, 0x25, 0xac, 0x13, 0x78, 0x7c, 0x24, 0xc0,
	0x5a, 0x8f, 0xce, 0x09, 0xaf, 0xa0, 0x7f, 0x78, 0x42, 0x29, 0x74, 0x73, 0xb9, 0x56, 0x8e, 0x70,
	0x20, 0x9c, 0xb6, 0x5e, 0xa4, 0x93, 0xed, 0x01, 0xc7, 0xe9, 0xf0, 0x15, 0x7c, 0x47, 0x4c, 0xcf,
	0xda, 0x1c, 0xd3, 0x26, 0x47, 0x13, 0xe2, 0x14, 0x26, 0xce, 0x5e, 0x65, 0x3a, 0x96, 0x15, 0xea,
	0xdc, 0x95, 0x1b, 0x88, 0xb1, 0x73, 0x1f, 0x0e, 0x66, 0xb8, 0x86, 0x6e, 0xcd, 0x51, 0xc8, 0x2a,
	0xad, 0x39, 0xac, 0xfe, 0x61, 0xeb, 0x34, 0xd8, 0xfe, 0x43, 0x0f, 0xcb, 0x55, 0x82, 0x86, 0x79,
	0x01, 0xe1, 0x7f, 0x84, 0x8f, 0xe5, 0x2d, 0x1a, 0x9b, 0x5a, 0xe2, 0x4e, 0xb1, 0x6e, 0x40, 0xb8,
	0x27, 0x9c, 0xb6, 0x9e, 0xed, 0x99, 0xf9, 0xfb, 0x36, 0xac, 0x9e, 0xbf, 0xd8, 0xb1, 0x4a, 0x13,
	0xa7, 0x76, 0xb8, 0x18, 0x2b, 0xba, 0x80, 0xfe, 0xd2, 0xe8, 0x0f, 0x15, 0x57, 0xf4, 0xa8, 0xd9,
	0x4a, 0x6b, 0x91, 0xc7, 0xad, 0x50, 0x6b, 0x2f, 0x9c, 0x5c, 0x92, 0xa8, 0xe7, 0xfe, 0xc2, 0xf5,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x2f, 0xf0, 0x29, 0x1d, 0x02, 0x00, 0x00,
}
