// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nixbuild.proto

package nixbuildpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientPayload struct {
	Build                *Build   `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	Zip                  []byte   `protobuf:"bytes,2,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientPayload) Reset()         { *m = ClientPayload{} }
func (m *ClientPayload) String() string { return proto.CompactTextString(m) }
func (*ClientPayload) ProtoMessage()    {}
func (*ClientPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{0}
}

func (m *ClientPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientPayload.Unmarshal(m, b)
}
func (m *ClientPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientPayload.Marshal(b, m, deterministic)
}
func (m *ClientPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientPayload.Merge(m, src)
}
func (m *ClientPayload) XXX_Size() int {
	return xxx_messageInfo_ClientPayload.Size(m)
}
func (m *ClientPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ClientPayload proto.InternalMessageInfo

func (m *ClientPayload) GetBuild() *Build {
	if m != nil {
		return m.Build
	}
	return nil
}

func (m *ClientPayload) GetZip() []byte {
	if m != nil {
		return m.Zip
	}
	return nil
}

type ServerPayload struct {
	Files                []*OutFile `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	HashNeeded           [][]byte   `protobuf:"bytes,2,rep,name=hash_needed,json=hashNeeded,proto3" json:"hash_needed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServerPayload) Reset()         { *m = ServerPayload{} }
func (m *ServerPayload) String() string { return proto.CompactTextString(m) }
func (*ServerPayload) ProtoMessage()    {}
func (*ServerPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{1}
}

func (m *ServerPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerPayload.Unmarshal(m, b)
}
func (m *ServerPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerPayload.Marshal(b, m, deterministic)
}
func (m *ServerPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerPayload.Merge(m, src)
}
func (m *ServerPayload) XXX_Size() int {
	return xxx_messageInfo_ServerPayload.Size(m)
}
func (m *ServerPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ServerPayload proto.InternalMessageInfo

func (m *ServerPayload) GetFiles() []*OutFile {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *ServerPayload) GetHashNeeded() [][]byte {
	if m != nil {
		return m.HashNeeded
	}
	return nil
}

type OutFile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutFile) Reset()         { *m = OutFile{} }
func (m *OutFile) String() string { return proto.CompactTextString(m) }
func (*OutFile) ProtoMessage()    {}
func (*OutFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{2}
}

func (m *OutFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutFile.Unmarshal(m, b)
}
func (m *OutFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutFile.Marshal(b, m, deterministic)
}
func (m *OutFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutFile.Merge(m, src)
}
func (m *OutFile) XXX_Size() int {
	return xxx_messageInfo_OutFile.Size(m)
}
func (m *OutFile) XXX_DiscardUnknown() {
	xxx_messageInfo_OutFile.DiscardUnknown(m)
}

var xxx_messageInfo_OutFile proto.InternalMessageInfo

func (m *OutFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OutFile) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Build struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Files                []*File  `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	BuildLocation        string   `protobuf:"bytes,3,opt,name=build_location,json=buildLocation,proto3" json:"build_location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{3}
}

func (m *Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build.Unmarshal(m, b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build.Marshal(b, m, deterministic)
}
func (m *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(m, src)
}
func (m *Build) XXX_Size() int {
	return xxx_messageInfo_Build.Size(m)
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

func (m *Build) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Build) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *Build) GetBuildLocation() string {
	if m != nil {
		return m.BuildLocation
	}
	return ""
}

type File struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsDir                bool     `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Hash                 []byte   `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac32869e13b7ce8, []int{4}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientPayload)(nil), "nixbuildpb.ClientPayload")
	proto.RegisterType((*ServerPayload)(nil), "nixbuildpb.ServerPayload")
	proto.RegisterType((*OutFile)(nil), "nixbuildpb.OutFile")
	proto.RegisterType((*Build)(nil), "nixbuildpb.Build")
	proto.RegisterType((*File)(nil), "nixbuildpb.File")
}

func init() { proto.RegisterFile("nixbuild.proto", fileDescriptor_7ac32869e13b7ce8) }

var fileDescriptor_7ac32869e13b7ce8 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcb, 0x4e, 0xeb, 0x30,
	0x10, 0x86, 0xe5, 0xa4, 0xe9, 0x39, 0x4c, 0x2f, 0x2a, 0x46, 0x48, 0x86, 0x0d, 0x51, 0x24, 0x20,
	0x6c, 0x2a, 0x28, 0x4f, 0xc0, 0x45, 0x2c, 0x10, 0xe2, 0x62, 0x96, 0x2c, 0xaa, 0xa4, 0x31, 0xea,
	0x20, 0x37, 0x8e, 0x92, 0x14, 0xd1, 0x3e, 0x3d, 0xf2, 0xb4, 0x86, 0x44, 0x62, 0x95, 0x3f, 0xff,
	0x8c, 0x67, 0xbe, 0xf1, 0x18, 0x86, 0x39, 0x7e, 0xa5, 0x4b, 0xd4, 0xd9, 0xb8, 0x28, 0x4d, 0x6d,
	0x38, 0xb8, 0xff, 0x22, 0x8d, 0xee, 0x61, 0x70, 0xa3, 0x51, 0xe5, 0xf5, 0x73, 0xb2, 0xd2, 0x26,
	0xc9, 0xf8, 0x29, 0x04, 0x14, 0x13, 0x2c, 0x64, 0x71, 0x6f, 0xb2, 0x3b, 0xfe, 0x4d, 0x1e, 0x5f,
	0xdb, 0xaf, 0xdc, 0xc4, 0xf9, 0x08, 0xfc, 0x35, 0x16, 0xc2, 0x0b, 0x59, 0xdc, 0x97, 0x56, 0x46,
	0x6f, 0x30, 0x78, 0x55, 0xe5, 0xa7, 0x2a, 0x5d, 0xad, 0x33, 0x08, 0xde, 0x51, 0xab, 0x4a, 0xb0,
	0xd0, 0x8f, 0x7b, 0x93, 0xbd, 0x66, 0xad, 0xa7, 0x65, 0x7d, 0x87, 0x5a, 0xc9, 0x4d, 0x06, 0x3f,
	0x82, 0xde, 0x3c, 0xa9, 0xe6, 0xd3, 0x5c, 0xa9, 0x4c, 0x65, 0xc2, 0x0b, 0xfd, 0xb8, 0x2f, 0xc1,
	0x5a, 0x8f, 0xe4, 0x44, 0x17, 0xf0, 0x6f, 0x7b, 0x84, 0x73, 0xe8, 0xe4, 0xc9, 0x42, 0x11, 0xe1,
	0x8e, 0x24, 0x6d, 0xbd, 0xd4, 0x64, 0xab, 0x2d, 0x0e, 0xe9, 0xe8, 0x03, 0x02, 0x22, 0xfe, 0xf3,
	0xc0, 0x89, 0x63, 0xf3, 0x88, 0x6d, 0xd4, 0x64, 0x6b, 0x82, 0x1d, 0xc3, 0x90, 0xec, 0xa9, 0x36,
	0xb3, 0xa4, 0x46, 0x93, 0x0b, 0x9f, 0xaa, 0x0c, 0xc8, 0x7d, 0xd8, 0x9a, 0xd1, 0x02, 0x3a, 0x8e,
	0xad, 0x48, 0xea, 0xb9, 0x6b, 0x65, 0xf5, 0x4f, 0x7b, 0xaf, 0xd1, 0x7e, 0x1f, 0xba, 0x58, 0x4d,
	0x33, 0x2c, 0xa9, 0xdc, 0x7f, 0x19, 0x60, 0x75, 0x8b, 0xa5, 0x4d, 0xad, 0x70, 0xad, 0x44, 0x27,
	0x64, 0xb1, 0x2f, 0x49, 0x5b, 0xcf, 0xde, 0x83, 0x08, 0x36, 0xa3, 0x59, 0x3d, 0x79, 0x81, 0x3e,
	0x8d, 0x66, 0xef, 0x1b, 0x67, 0x8a, 0x5f, 0xb9, 0x51, 0x0f, 0x9a, 0x73, 0xb4, 0x36, 0x7b, 0xd8,
	0x0a, 0xb5, 0x16, 0x15, 0xb3, 0x73, 0x96, 0x76, 0xe9, 0x71, 0x5c, 0x7e, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x93, 0x3d, 0x6f, 0xcc, 0x2e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BuildServiceClient is the client API for BuildService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BuildServiceClient interface {
	Build(ctx context.Context, opts ...grpc.CallOption) (BuildService_BuildClient, error)
}

type buildServiceClient struct {
	cc *grpc.ClientConn
}

func NewBuildServiceClient(cc *grpc.ClientConn) BuildServiceClient {
	return &buildServiceClient{cc}
}

func (c *buildServiceClient) Build(ctx context.Context, opts ...grpc.CallOption) (BuildService_BuildClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BuildService_serviceDesc.Streams[0], "/nixbuildpb.BuildService/Build", opts...)
	if err != nil {
		return nil, err
	}
	x := &buildServiceBuildClient{stream}
	return x, nil
}

type BuildService_BuildClient interface {
	Send(*ClientPayload) error
	Recv() (*ServerPayload, error)
	grpc.ClientStream
}

type buildServiceBuildClient struct {
	grpc.ClientStream
}

func (x *buildServiceBuildClient) Send(m *ClientPayload) error {
	return x.ClientStream.SendMsg(m)
}

func (x *buildServiceBuildClient) Recv() (*ServerPayload, error) {
	m := new(ServerPayload)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BuildServiceServer is the server API for BuildService service.
type BuildServiceServer interface {
	Build(BuildService_BuildServer) error
}

// UnimplementedBuildServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBuildServiceServer struct {
}

func (*UnimplementedBuildServiceServer) Build(srv BuildService_BuildServer) error {
	return status.Errorf(codes.Unimplemented, "method Build not implemented")
}

func RegisterBuildServiceServer(s *grpc.Server, srv BuildServiceServer) {
	s.RegisterService(&_BuildService_serviceDesc, srv)
}

func _BuildService_Build_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BuildServiceServer).Build(&buildServiceBuildServer{stream})
}

type BuildService_BuildServer interface {
	Send(*ServerPayload) error
	Recv() (*ClientPayload, error)
	grpc.ServerStream
}

type buildServiceBuildServer struct {
	grpc.ServerStream
}

func (x *buildServiceBuildServer) Send(m *ServerPayload) error {
	return x.ServerStream.SendMsg(m)
}

func (x *buildServiceBuildServer) Recv() (*ClientPayload, error) {
	m := new(ClientPayload)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _BuildService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nixbuildpb.BuildService",
	HandlerType: (*BuildServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Build",
			Handler:       _BuildService_Build_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "nixbuild.proto",
}
