// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transport.proto

package transport

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Query_QueryType int32

const (
	Query_RECORD_QUERY  Query_QueryType = 0
	Query_DELETE_WHERE  Query_QueryType = 1
	Query_DELETE_RECORD Query_QueryType = 2
	Query_LOAD_RECORD   Query_QueryType = 3
)

var Query_QueryType_name = map[int32]string{
	0: "RECORD_QUERY",
	1: "DELETE_WHERE",
	2: "DELETE_RECORD",
	3: "LOAD_RECORD",
}

var Query_QueryType_value = map[string]int32{
	"RECORD_QUERY":  0,
	"DELETE_WHERE":  1,
	"DELETE_RECORD": 2,
	"LOAD_RECORD":   3,
}

func (x Query_QueryType) String() string {
	return proto.EnumName(Query_QueryType_name, int32(x))
}

func (Query_QueryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{6, 0}
}

type QueryComponent_ComponentType int32

const (
	QueryComponent_AND   QueryComponent_ComponentType = 0
	QueryComponent_OR    QueryComponent_ComponentType = 1
	QueryComponent_NOT   QueryComponent_ComponentType = 2
	QueryComponent_FIELD QueryComponent_ComponentType = 3
)

var QueryComponent_ComponentType_name = map[int32]string{
	0: "AND",
	1: "OR",
	2: "NOT",
	3: "FIELD",
}

var QueryComponent_ComponentType_value = map[string]int32{
	"AND":   0,
	"OR":    1,
	"NOT":   2,
	"FIELD": 3,
}

func (x QueryComponent_ComponentType) String() string {
	return proto.EnumName(QueryComponent_ComponentType_name, int32(x))
}

func (QueryComponent_ComponentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{9, 0}
}

type Field_ComponentType int32

const (
	Field_EQUALS       Field_ComponentType = 0
	Field_GREATER_THAN Field_ComponentType = 1
	Field_LESS_THAN    Field_ComponentType = 2
	Field_EMPTY        Field_ComponentType = 3
	Field_NOT_EMPTY    Field_ComponentType = 4
	Field_IS_NULL      Field_ComponentType = 5
	Field_MATCHES      Field_ComponentType = 6
)

var Field_ComponentType_name = map[int32]string{
	0: "EQUALS",
	1: "GREATER_THAN",
	2: "LESS_THAN",
	3: "EMPTY",
	4: "NOT_EMPTY",
	5: "IS_NULL",
	6: "MATCHES",
}

var Field_ComponentType_value = map[string]int32{
	"EQUALS":       0,
	"GREATER_THAN": 1,
	"LESS_THAN":    2,
	"EMPTY":        3,
	"NOT_EMPTY":    4,
	"IS_NULL":      5,
	"MATCHES":      6,
}

func (x Field_ComponentType) String() string {
	return proto.EnumName(Field_ComponentType_name, int32(x))
}

func (Field_ComponentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{10, 0}
}

type Value_ValueType int32

const (
	Value_DOUBLE Value_ValueType = 0
	Value_FLOAT  Value_ValueType = 1
	Value_INT32  Value_ValueType = 2
	Value_INT64  Value_ValueType = 3
	Value_SINT32 Value_ValueType = 5
	Value_SINT64 Value_ValueType = 6
	Value_BOOL   Value_ValueType = 9
	Value_STRING Value_ValueType = 10
	Value_BYTES  Value_ValueType = 11
)

var Value_ValueType_name = map[int32]string{
	0:  "DOUBLE",
	1:  "FLOAT",
	2:  "INT32",
	3:  "INT64",
	5:  "SINT32",
	6:  "SINT64",
	9:  "BOOL",
	10: "STRING",
	11: "BYTES",
}

var Value_ValueType_value = map[string]int32{
	"DOUBLE": 0,
	"FLOAT":  1,
	"INT32":  2,
	"INT64":  3,
	"SINT32": 5,
	"SINT64": 6,
	"BOOL":   9,
	"STRING": 10,
	"BYTES":  11,
}

func (x Value_ValueType) String() string {
	return proto.EnumName(Value_ValueType_name, int32(x))
}

func (Value_ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{11, 0}
}

type Request struct {
	Token                string    `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Insertions           []*Insert `protobuf:"bytes,6,rep,name=insertions,proto3" json:"insertions,omitempty"`
	Query                *Query    `protobuf:"bytes,7,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Request) GetInsertions() []*Insert {
	if m != nil {
		return m.Insertions
	}
	return nil
}

func (m *Request) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

type Response struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Records              [][]byte `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetRecords() [][]byte {
	if m != nil {
		return m.Records
	}
	return nil
}

type LoginRequest struct {
	Username             string    `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string    `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Keyspace             string    `protobuf:"bytes,3,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	FileDescriptor       []byte    `protobuf:"bytes,4,opt,name=file_descriptor,json=fileDescriptor,proto3" json:"file_descriptor,omitempty"`
	Records              []*Record `protobuf:"bytes,5,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *LoginRequest) GetFileDescriptor() []byte {
	if m != nil {
		return m.FileDescriptor
	}
	return nil
}

func (m *LoginRequest) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type Record struct {
	FieldOptions         map[string]*FieldOptions `protobuf:"bytes,1,rep,name=field_options,json=fieldOptions,proto3" json:"field_options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Name                 string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{3}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetFieldOptions() map[string]*FieldOptions {
	if m != nil {
		return m.FieldOptions
	}
	return nil
}

func (m *Record) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// from record_metadata_options.proto
type FieldOptions struct {
	PrimaryKey           bool                      `protobuf:"varint,2,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	Index                *FieldOptions_IndexOption `protobuf:"bytes,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *FieldOptions) Reset()         { *m = FieldOptions{} }
func (m *FieldOptions) String() string { return proto.CompactTextString(m) }
func (*FieldOptions) ProtoMessage()    {}
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{4}
}

func (m *FieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldOptions.Unmarshal(m, b)
}
func (m *FieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldOptions.Marshal(b, m, deterministic)
}
func (m *FieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldOptions.Merge(m, src)
}
func (m *FieldOptions) XXX_Size() int {
	return xxx_messageInfo_FieldOptions.Size(m)
}
func (m *FieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_FieldOptions proto.InternalMessageInfo

func (m *FieldOptions) GetPrimaryKey() bool {
	if m != nil {
		return m.PrimaryKey
	}
	return false
}

func (m *FieldOptions) GetIndex() *FieldOptions_IndexOption {
	if m != nil {
		return m.Index
	}
	return nil
}

type FieldOptions_IndexOption struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Unique               bool     `protobuf:"varint,2,opt,name=unique,proto3" json:"unique,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldOptions_IndexOption) Reset()         { *m = FieldOptions_IndexOption{} }
func (m *FieldOptions_IndexOption) String() string { return proto.CompactTextString(m) }
func (*FieldOptions_IndexOption) ProtoMessage()    {}
func (*FieldOptions_IndexOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{4, 0}
}

func (m *FieldOptions_IndexOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldOptions_IndexOption.Unmarshal(m, b)
}
func (m *FieldOptions_IndexOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldOptions_IndexOption.Marshal(b, m, deterministic)
}
func (m *FieldOptions_IndexOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldOptions_IndexOption.Merge(m, src)
}
func (m *FieldOptions_IndexOption) XXX_Size() int {
	return xxx_messageInfo_FieldOptions_IndexOption.Size(m)
}
func (m *FieldOptions_IndexOption) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldOptions_IndexOption.DiscardUnknown(m)
}

var xxx_messageInfo_FieldOptions_IndexOption proto.InternalMessageInfo

func (m *FieldOptions_IndexOption) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FieldOptions_IndexOption) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{5}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Query struct {
	RecordQuery          *RecordQuery       `protobuf:"bytes,1,opt,name=record_query,json=recordQuery,proto3" json:"record_query,omitempty"`
	ExecuteProperties    *ExecuteProperties `protobuf:"bytes,4,opt,name=execute_properties,json=executeProperties,proto3" json:"execute_properties,omitempty"`
	PrimaryKey           *Value             `protobuf:"bytes,5,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	QueryType            Query_QueryType    `protobuf:"varint,3,opt,name=query_type,json=queryType,proto3,enum=vinyl.Query_QueryType" json:"query_type,omitempty"`
	RecordType           string             `protobuf:"bytes,6,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{6}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetRecordQuery() *RecordQuery {
	if m != nil {
		return m.RecordQuery
	}
	return nil
}

func (m *Query) GetExecuteProperties() *ExecuteProperties {
	if m != nil {
		return m.ExecuteProperties
	}
	return nil
}

func (m *Query) GetPrimaryKey() *Value {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

func (m *Query) GetQueryType() Query_QueryType {
	if m != nil {
		return m.QueryType
	}
	return Query_RECORD_QUERY
}

func (m *Query) GetRecordType() string {
	if m != nil {
		return m.RecordType
	}
	return ""
}

type RecordQuery struct {
	Filter               *QueryComponent `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RecordQuery) Reset()         { *m = RecordQuery{} }
func (m *RecordQuery) String() string { return proto.CompactTextString(m) }
func (*RecordQuery) ProtoMessage()    {}
func (*RecordQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{7}
}

func (m *RecordQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordQuery.Unmarshal(m, b)
}
func (m *RecordQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordQuery.Marshal(b, m, deterministic)
}
func (m *RecordQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordQuery.Merge(m, src)
}
func (m *RecordQuery) XXX_Size() int {
	return xxx_messageInfo_RecordQuery.Size(m)
}
func (m *RecordQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordQuery.DiscardUnknown(m)
}

var xxx_messageInfo_RecordQuery proto.InternalMessageInfo

func (m *RecordQuery) GetFilter() *QueryComponent {
	if m != nil {
		return m.Filter
	}
	return nil
}

type ExecuteProperties struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip                 int32    `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteProperties) Reset()         { *m = ExecuteProperties{} }
func (m *ExecuteProperties) String() string { return proto.CompactTextString(m) }
func (*ExecuteProperties) ProtoMessage()    {}
func (*ExecuteProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{8}
}

func (m *ExecuteProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteProperties.Unmarshal(m, b)
}
func (m *ExecuteProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteProperties.Marshal(b, m, deterministic)
}
func (m *ExecuteProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteProperties.Merge(m, src)
}
func (m *ExecuteProperties) XXX_Size() int {
	return xxx_messageInfo_ExecuteProperties.Size(m)
}
func (m *ExecuteProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteProperties.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteProperties proto.InternalMessageInfo

func (m *ExecuteProperties) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ExecuteProperties) GetSkip() int32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

type QueryComponent struct {
	Child                *QueryComponent              `protobuf:"bytes,1,opt,name=child,proto3" json:"child,omitempty"`
	Children             []*QueryComponent            `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	ComponentType        QueryComponent_ComponentType `protobuf:"varint,3,opt,name=component_type,json=componentType,proto3,enum=vinyl.QueryComponent_ComponentType" json:"component_type,omitempty"`
	Field                *Field                       `protobuf:"bytes,4,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *QueryComponent) Reset()         { *m = QueryComponent{} }
func (m *QueryComponent) String() string { return proto.CompactTextString(m) }
func (*QueryComponent) ProtoMessage()    {}
func (*QueryComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{9}
}

func (m *QueryComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryComponent.Unmarshal(m, b)
}
func (m *QueryComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryComponent.Marshal(b, m, deterministic)
}
func (m *QueryComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryComponent.Merge(m, src)
}
func (m *QueryComponent) XXX_Size() int {
	return xxx_messageInfo_QueryComponent.Size(m)
}
func (m *QueryComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryComponent.DiscardUnknown(m)
}

var xxx_messageInfo_QueryComponent proto.InternalMessageInfo

func (m *QueryComponent) GetChild() *QueryComponent {
	if m != nil {
		return m.Child
	}
	return nil
}

func (m *QueryComponent) GetChildren() []*QueryComponent {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *QueryComponent) GetComponentType() QueryComponent_ComponentType {
	if m != nil {
		return m.ComponentType
	}
	return QueryComponent_AND
}

func (m *QueryComponent) GetField() *Field {
	if m != nil {
		return m.Field
	}
	return nil
}

type Field struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                *Value              `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ComponentType        Field_ComponentType `protobuf:"varint,3,opt,name=component_type,json=componentType,proto3,enum=vinyl.Field_ComponentType" json:"component_type,omitempty"`
	Matches              *QueryComponent     `protobuf:"bytes,4,opt,name=matches,proto3" json:"matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{10}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Field) GetComponentType() Field_ComponentType {
	if m != nil {
		return m.ComponentType
	}
	return Field_EQUALS
}

func (m *Field) GetMatches() *QueryComponent {
	if m != nil {
		return m.Matches
	}
	return nil
}

type Value struct {
	Double float64 `protobuf:"fixed64,1,opt,name=double,proto3" json:"double,omitempty"`
	Float  float32 `protobuf:"fixed32,2,opt,name=float,proto3" json:"float,omitempty"`
	Int32  int32   `protobuf:"varint,3,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64  int64   `protobuf:"varint,4,opt,name=int64,proto3" json:"int64,omitempty"`
	// uint32 not supported
	// uint64 not supported
	Sint32 int32 `protobuf:"zigzag32,6,opt,name=sint32,proto3" json:"sint32,omitempty"`
	Sint64 int64 `protobuf:"zigzag64,7,opt,name=sint64,proto3" json:"sint64,omitempty"`
	// fixed32 not supported
	// fixed64 not supported
	Bool                 bool            `protobuf:"varint,10,opt,name=bool,proto3" json:"bool,omitempty"`
	String_              string          `protobuf:"bytes,11,opt,name=string,proto3" json:"string,omitempty"`
	Bytes                []byte          `protobuf:"bytes,12,opt,name=bytes,proto3" json:"bytes,omitempty"`
	ValueType            Value_ValueType `protobuf:"varint,20,opt,name=value_type,json=valueType,proto3,enum=vinyl.Value_ValueType" json:"value_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{11}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetDouble() float64 {
	if m != nil {
		return m.Double
	}
	return 0
}

func (m *Value) GetFloat() float32 {
	if m != nil {
		return m.Float
	}
	return 0
}

func (m *Value) GetInt32() int32 {
	if m != nil {
		return m.Int32
	}
	return 0
}

func (m *Value) GetInt64() int64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

func (m *Value) GetSint32() int32 {
	if m != nil {
		return m.Sint32
	}
	return 0
}

func (m *Value) GetSint64() int64 {
	if m != nil {
		return m.Sint64
	}
	return 0
}

func (m *Value) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

func (m *Value) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func (m *Value) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *Value) GetValueType() Value_ValueType {
	if m != nil {
		return m.ValueType
	}
	return Value_DOUBLE
}

type Insert struct {
	Record               string   `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Insert) Reset()         { *m = Insert{} }
func (m *Insert) String() string { return proto.CompactTextString(m) }
func (*Insert) ProtoMessage()    {}
func (*Insert) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{12}
}

func (m *Insert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Insert.Unmarshal(m, b)
}
func (m *Insert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Insert.Marshal(b, m, deterministic)
}
func (m *Insert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Insert.Merge(m, src)
}
func (m *Insert) XXX_Size() int {
	return xxx_messageInfo_Insert.Size(m)
}
func (m *Insert) XXX_DiscardUnknown() {
	xxx_messageInfo_Insert.DiscardUnknown(m)
}

var xxx_messageInfo_Insert proto.InternalMessageInfo

func (m *Insert) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

func (m *Insert) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("vinyl.Query_QueryType", Query_QueryType_name, Query_QueryType_value)
	proto.RegisterEnum("vinyl.QueryComponent_ComponentType", QueryComponent_ComponentType_name, QueryComponent_ComponentType_value)
	proto.RegisterEnum("vinyl.Field_ComponentType", Field_ComponentType_name, Field_ComponentType_value)
	proto.RegisterEnum("vinyl.Value_ValueType", Value_ValueType_name, Value_ValueType_value)
	proto.RegisterType((*Request)(nil), "vinyl.Request")
	proto.RegisterType((*Response)(nil), "vinyl.Response")
	proto.RegisterType((*LoginRequest)(nil), "vinyl.LoginRequest")
	proto.RegisterType((*Record)(nil), "vinyl.Record")
	proto.RegisterMapType((map[string]*FieldOptions)(nil), "vinyl.Record.FieldOptionsEntry")
	proto.RegisterType((*FieldOptions)(nil), "vinyl.FieldOptions")
	proto.RegisterType((*FieldOptions_IndexOption)(nil), "vinyl.FieldOptions.IndexOption")
	proto.RegisterType((*LoginResponse)(nil), "vinyl.LoginResponse")
	proto.RegisterType((*Query)(nil), "vinyl.Query")
	proto.RegisterType((*RecordQuery)(nil), "vinyl.RecordQuery")
	proto.RegisterType((*ExecuteProperties)(nil), "vinyl.ExecuteProperties")
	proto.RegisterType((*QueryComponent)(nil), "vinyl.QueryComponent")
	proto.RegisterType((*Field)(nil), "vinyl.Field")
	proto.RegisterType((*Value)(nil), "vinyl.Value")
	proto.RegisterType((*Insert)(nil), "vinyl.Insert")
}

func init() { proto.RegisterFile("transport.proto", fileDescriptor_a97e32c760ec1b28) }

var fileDescriptor_a97e32c760ec1b28 = []byte{
	// 1130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x36, 0x29, 0x93, 0x92, 0x86, 0x94, 0x4d, 0x6f, 0xd3, 0x80, 0xf0, 0x25, 0x06, 0x7b, 0x88,
	0xdb, 0x22, 0x2a, 0x2a, 0x2b, 0x46, 0x9b, 0xb6, 0x07, 0xd9, 0x62, 0x6c, 0xb5, 0x8c, 0x14, 0xaf,
	0xe8, 0x14, 0xee, 0x85, 0x90, 0xa5, 0x75, 0x42, 0x58, 0x26, 0xe9, 0x25, 0xe5, 0x46, 0x2f, 0xd2,
	0x7b, 0x0f, 0x7d, 0x83, 0x1e, 0xfa, 0x3e, 0x7d, 0x8e, 0x02, 0xc5, 0xce, 0x92, 0x14, 0xe5, 0xc4,
	0xb9, 0x10, 0xf3, 0x7d, 0x33, 0xb3, 0xbb, 0xf3, 0xb3, 0xb3, 0x84, 0xed, 0x8c, 0x4f, 0xa2, 0x34,
	0x89, 0x79, 0xd6, 0x4e, 0x78, 0x9c, 0xc5, 0x44, 0xbb, 0x0b, 0xa3, 0xe5, 0xdc, 0xe1, 0x50, 0xa7,
	0xec, 0x76, 0xc1, 0xd2, 0x8c, 0x3c, 0x02, 0x2d, 0x8b, 0xaf, 0x59, 0x64, 0x2b, 0x7b, 0xca, 0x7e,
	0x93, 0x4a, 0x40, 0x9e, 0x01, 0x84, 0x51, 0xca, 0x78, 0x16, 0xc6, 0x51, 0x6a, 0xeb, 0x7b, 0xb5,
	0x7d, 0xa3, 0xd3, 0x6a, 0xa3, 0x73, 0x7b, 0x80, 0x0a, 0x5a, 0x31, 0x20, 0x0e, 0x68, 0xb7, 0x0b,
	0xc6, 0x97, 0x76, 0x7d, 0x4f, 0xd9, 0x37, 0x3a, 0x66, 0x6e, 0x79, 0x26, 0x38, 0x2a, 0x55, 0xce,
	0x0b, 0x68, 0x50, 0x96, 0x26, 0x71, 0x94, 0x32, 0xb1, 0x29, 0xe3, 0x3c, 0xe6, 0xc5, 0xa6, 0x08,
	0x88, 0x0d, 0x75, 0xce, 0xa6, 0x31, 0x9f, 0xa5, 0xb6, 0xba, 0x57, 0xdb, 0x37, 0x69, 0x01, 0x9d,
	0xbf, 0x15, 0x30, 0xbd, 0xf8, 0x6d, 0x18, 0x15, 0xa7, 0xde, 0x85, 0xc6, 0x22, 0x65, 0x3c, 0x9a,
	0xdc, 0xb0, 0x7c, 0x8d, 0x12, 0x0b, 0x5d, 0x32, 0x49, 0xd3, 0xdf, 0x63, 0x3e, 0xb3, 0x55, 0xa9,
	0x2b, 0xb0, 0xd0, 0x5d, 0xb3, 0x65, 0x9a, 0x4c, 0xa6, 0xcc, 0xae, 0x49, 0x5d, 0x81, 0xc9, 0x53,
	0xd8, 0xbe, 0x0a, 0xe7, 0x2c, 0x98, 0xb1, 0x74, 0xca, 0xc3, 0x24, 0x8b, 0xb9, 0xbd, 0xb9, 0xa7,
	0xec, 0x9b, 0x74, 0x4b, 0xd0, 0xfd, 0x92, 0x25, 0x4f, 0x57, 0xe7, 0xd4, 0xd6, 0x32, 0x43, 0x91,
	0x5d, 0x1d, 0xfb, 0x1f, 0x05, 0x74, 0xc9, 0x91, 0x3e, 0xb4, 0xae, 0x42, 0x36, 0x9f, 0x05, 0x71,
	0x22, 0x73, 0xaa, 0xa0, 0xe7, 0x93, 0x35, 0xcf, 0xf6, 0x4b, 0x61, 0x32, 0x92, 0x16, 0x6e, 0x94,
	0xf1, 0x25, 0x35, 0xaf, 0x2a, 0x14, 0x21, 0xb0, 0x89, 0x21, 0xcb, 0xb0, 0x50, 0xde, 0xf5, 0x61,
	0xe7, 0x03, 0x37, 0x62, 0x41, 0xed, 0x9a, 0x2d, 0xf3, 0xd4, 0x08, 0x91, 0x7c, 0x09, 0xda, 0xdd,
	0x64, 0xbe, 0x90, 0xbe, 0x46, 0xe7, 0xb3, 0x7c, 0xe3, 0xaa, 0x2b, 0x95, 0x16, 0x2f, 0xd4, 0xef,
	0x14, 0xe7, 0x4f, 0x05, 0xcc, 0xaa, 0x8e, 0x3c, 0x01, 0x23, 0xe1, 0xe1, 0xcd, 0x84, 0x2f, 0x03,
	0xb1, 0xb2, 0x58, 0xa5, 0x41, 0x21, 0xa7, 0x7e, 0x61, 0x4b, 0xf2, 0x1c, 0xb4, 0x30, 0x9a, 0xb1,
	0xf7, 0x98, 0xd7, 0x55, 0x64, 0xd5, 0x45, 0xda, 0x03, 0x61, 0x20, 0x01, 0x95, 0xd6, 0xbb, 0xdf,
	0x83, 0x51, 0x61, 0x45, 0x84, 0xd9, 0x32, 0x29, 0x8a, 0x8a, 0x32, 0x79, 0x0c, 0xfa, 0x22, 0x0a,
	0x6f, 0xf3, 0xb3, 0x37, 0x68, 0x8e, 0x9c, 0x1f, 0xa0, 0x95, 0x37, 0xc5, 0xaa, 0xad, 0x3e, 0xd2,
	0xcb, 0x65, 0xb3, 0xa9, 0x95, 0x66, 0x73, 0xfe, 0x55, 0x41, 0xc3, 0xfe, 0x24, 0xcf, 0xc1, 0x94,
	0x05, 0x0b, 0x64, 0x0f, 0x2b, 0x78, 0x7e, 0xb2, 0x56, 0x19, 0xd9, 0xc9, 0x06, 0x5f, 0x01, 0x72,
	0x02, 0x84, 0xbd, 0x67, 0xd3, 0x45, 0xc6, 0x82, 0x84, 0xc7, 0x89, 0xb8, 0x0a, 0x2c, 0xc5, 0x8e,
	0x31, 0x3a, 0x76, 0xee, 0xec, 0x4a, 0x83, 0xd7, 0xa5, 0x9e, 0xee, 0xb0, 0xfb, 0x14, 0x79, 0xb6,
	0x9e, 0x59, 0x6d, 0xed, 0x0a, 0xbd, 0x11, 0x15, 0xb9, 0x97, 0x67, 0xc0, 0x73, 0x06, 0x98, 0x27,
	0x91, 0xec, 0xad, 0xce, 0xe3, 0xea, 0x85, 0x93, 0x5f, 0x7f, 0x99, 0x30, 0xda, 0xbc, 0x2d, 0x44,
	0x51, 0xbf, 0x3c, 0x4a, 0xf4, 0xd3, 0x31, 0x17, 0x20, 0x29, 0x61, 0xe0, 0x8c, 0xa1, 0x59, 0x3a,
	0x12, 0x0b, 0x4c, 0xea, 0x1e, 0x8f, 0x68, 0x3f, 0x38, 0x3b, 0x77, 0xe9, 0x85, 0xb5, 0x21, 0x98,
	0xbe, 0xeb, 0xb9, 0xbe, 0x1b, 0xfc, 0x7a, 0xea, 0x52, 0xd7, 0x52, 0xc8, 0x0e, 0xb4, 0x72, 0x46,
	0x9a, 0x5a, 0x2a, 0xd9, 0x06, 0xc3, 0x1b, 0xf5, 0xfa, 0x05, 0x51, 0x73, 0x7e, 0x04, 0xa3, 0x92,
	0x40, 0xf2, 0x0c, 0xf4, 0xab, 0x70, 0x9e, 0x31, 0x9e, 0x27, 0xf9, 0xf3, 0xea, 0xb9, 0x8f, 0xe3,
	0x9b, 0x24, 0x8e, 0x58, 0x94, 0xd1, 0xdc, 0xc8, 0xf9, 0x09, 0x76, 0x3e, 0xc8, 0xa0, 0x28, 0xe7,
	0x3c, 0xbc, 0x09, 0x33, 0x5c, 0x42, 0xa3, 0x12, 0x88, 0xbe, 0x49, 0xaf, 0xc3, 0x04, 0x6b, 0xac,
	0x51, 0x94, 0x9d, 0x3f, 0x54, 0xd8, 0x5a, 0x5f, 0x99, 0x7c, 0x0d, 0xda, 0xf4, 0x5d, 0x38, 0x9f,
	0x7d, 0x7a, 0x7f, 0x69, 0x43, 0xbe, 0x85, 0x06, 0x0a, 0x9c, 0x45, 0x38, 0x90, 0x1e, 0xb4, 0x2f,
	0xcd, 0xc8, 0xcf, 0xb0, 0x35, 0x2d, 0xe8, 0x6a, 0x81, 0xbe, 0xf8, 0xa8, 0x63, 0xbb, 0x94, 0xb0,
	0x5a, 0xad, 0x69, 0x15, 0x8a, 0xa1, 0x8a, 0x97, 0x3f, 0xef, 0x29, 0xb3, 0x7a, 0xa1, 0xa8, 0x54,
	0x39, 0x5d, 0x68, 0xad, 0xad, 0x41, 0xea, 0x50, 0xeb, 0x0d, 0xfb, 0xd6, 0x06, 0xd1, 0x41, 0x1d,
	0x51, 0x4b, 0x11, 0xc4, 0x70, 0xe4, 0x5b, 0x2a, 0x69, 0x82, 0xf6, 0x72, 0xe0, 0x7a, 0xa2, 0x2a,
	0x7f, 0xa9, 0xa0, 0xe1, 0x32, 0xe5, 0x40, 0x51, 0x56, 0x03, 0x45, 0xec, 0x5b, 0x9d, 0x14, 0xeb,
	0x9d, 0x28, 0x55, 0xa4, 0xf7, 0x40, 0x9c, 0xbb, 0xd5, 0x43, 0x7e, 0x3a, 0xbc, 0x6f, 0xa0, 0x7e,
	0x33, 0xc9, 0xa6, 0xef, 0xca, 0x4b, 0xf3, 0x40, 0x72, 0x0b, 0x2b, 0x27, 0xb9, 0x1f, 0x2b, 0x80,
	0xee, 0x9e, 0x9d, 0xf7, 0xbc, 0xb1, 0x6c, 0xcf, 0x13, 0xea, 0xf6, 0x7c, 0x97, 0x06, 0xfe, 0x69,
	0x6f, 0x68, 0x29, 0xa4, 0x05, 0x4d, 0xcf, 0x1d, 0x8f, 0x25, 0xc4, 0xf0, 0xdd, 0x57, 0xaf, 0xfd,
	0x0b, 0xab, 0x26, 0x34, 0xc3, 0x91, 0x1f, 0x48, 0xb8, 0x49, 0x0c, 0xa8, 0x0f, 0xc6, 0xc1, 0xf0,
	0xdc, 0xf3, 0x2c, 0x4d, 0x80, 0x57, 0x3d, 0xff, 0xf8, 0xd4, 0x1d, 0x5b, 0xba, 0xf3, 0x9f, 0x0a,
	0x1a, 0x86, 0x2d, 0x46, 0xd0, 0x2c, 0x5e, 0x5c, 0xce, 0x65, 0xa6, 0x14, 0x9a, 0x23, 0xd1, 0x8c,
	0x57, 0xf3, 0x78, 0x92, 0x61, 0xae, 0x54, 0x2a, 0x81, 0x60, 0xc3, 0x28, 0x3b, 0xe8, 0x60, 0x52,
	0x34, 0x2a, 0x41, 0xce, 0x1e, 0x76, 0x31, 0xdc, 0x1a, 0x95, 0x40, 0xac, 0x9c, 0x4a, 0x63, 0x71,
	0x25, 0x77, 0x68, 0x8e, 0x0a, 0xfe, 0xb0, 0x8b, 0x6f, 0x2a, 0xa1, 0x39, 0x12, 0x15, 0xbb, 0x8c,
	0xe3, 0xb9, 0x0d, 0x38, 0x0a, 0x51, 0x46, 0xdb, 0x8c, 0x87, 0xd1, 0x5b, 0xdb, 0xc0, 0x3a, 0xe6,
	0x48, 0xec, 0x78, 0xb9, 0xcc, 0x58, 0x6a, 0x9b, 0xf8, 0x8e, 0x49, 0x20, 0x06, 0x08, 0x16, 0x51,
	0xd6, 0xed, 0xd1, 0xda, 0x00, 0xc1, 0x68, 0xe5, 0x57, 0x0e, 0x90, 0xbb, 0x42, 0x74, 0x6e, 0xa1,
	0x59, 0xf2, 0x22, 0xf5, 0xfd, 0xd1, 0xf9, 0x91, 0xe7, 0x5a, 0x1b, 0xd8, 0x58, 0xde, 0xa8, 0xe7,
	0x5b, 0x8a, 0x10, 0x07, 0x43, 0xff, 0xa0, 0x23, 0xf3, 0x3d, 0x18, 0xfa, 0x87, 0x5d, 0xab, 0x26,
	0x8c, 0xc7, 0x92, 0xd6, 0x0a, 0xf9, 0xb0, 0x6b, 0xe9, 0xa4, 0x01, 0x9b, 0x47, 0xa3, 0x91, 0x67,
	0x35, 0x91, 0xf5, 0xe9, 0x60, 0x78, 0x62, 0x81, 0x70, 0x3c, 0xba, 0xf0, 0xdd, 0xb1, 0x65, 0x38,
	0x5d, 0xd0, 0xe5, 0xcf, 0x86, 0x88, 0x50, 0x8e, 0xaa, 0xbc, 0x53, 0x73, 0x24, 0xb2, 0x31, 0x9b,
	0x64, 0x13, 0x4c, 0xbf, 0x49, 0x51, 0xee, 0x84, 0xa0, 0xbd, 0x11, 0xc1, 0x90, 0x2e, 0x68, 0xf8,
	0x3e, 0x90, 0xe2, 0xb1, 0xab, 0xfe, 0x42, 0xec, 0x3e, 0x5a, 0x27, 0xe5, 0x13, 0xe2, 0x6c, 0x90,
	0xaf, 0x8a, 0x77, 0x61, 0xab, 0x7c, 0x01, 0xa4, 0xc3, 0x76, 0x89, 0x0b, 0xdb, 0x23, 0x02, 0xf2,
	0x87, 0xea, 0xb7, 0x66, 0xf9, 0xa3, 0x75, 0xa9, 0xe3, 0x9f, 0xd6, 0xc1, 0xff, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x4b, 0x10, 0x40, 0xa5, 0x7c, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VinylClient is the client API for Vinyl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VinylClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Query(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type vinylClient struct {
	cc *grpc.ClientConn
}

func NewVinylClient(cc *grpc.ClientConn) VinylClient {
	return &vinylClient{cc}
}

func (c *vinylClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/vinyl.Vinyl/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vinylClient) Query(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/vinyl.Vinyl/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VinylServer is the server API for Vinyl service.
type VinylServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Query(context.Context, *Request) (*Response, error)
}

// UnimplementedVinylServer can be embedded to have forward compatible implementations.
type UnimplementedVinylServer struct {
}

func (*UnimplementedVinylServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedVinylServer) Query(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}

func RegisterVinylServer(s *grpc.Server, srv VinylServer) {
	s.RegisterService(&_Vinyl_serviceDesc, srv)
}

func _Vinyl_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VinylServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vinyl.Vinyl/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VinylServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vinyl_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VinylServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vinyl.Vinyl/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VinylServer).Query(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Vinyl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vinyl.Vinyl",
	HandlerType: (*VinylServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Vinyl_Login_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Vinyl_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transport.proto",
}
